version: '2'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  hhnk:
    build: .
    depends_on:
      - db
    # Automatically pick up changes in the sql/ directory without needing to
    # re-build the entire docker. The "deploy" docker doesn't do this, so
    # there only the sql files present during docker generation are
    # available.
    volumes:
      - ./sql:/code/sql
