version: '2'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  hhnk:
    build: .
    depends_on:
      - db
<<<<<<< Updated upstream
=======
      - adminer
    # Automatically pick up changes in the sql/ directory without needing to
    # re-build the entire docker. The "deploy" docker doesn't do this, so
    # there only the files present during docker generation are
    # available. When running the container on Windows, share this folder under
    # Docker -> Settings -> Resources -> File sharing
    volumes:
      - ./sql:/code/sql
>>>>>>> Stashed changes
