version: '2'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  hhnk:
    image: docker.pkg.github.com/nens/hhnk-modelbuilder-temp/hhnk-modelbuilder
    depends_on:
      - db
